faile if exist is true

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,4 +1,4 @@
-name: Automatic Release
+name: Github Release
 
 on:
   pull_request:
@@ -45,6 +45,12 @@ jobs:
         if: env.exists == 'true'
         run: |
           gh issue create --title "Release $VERSION already exists" --body "The release for version $VERSION already exists. Please review and take appropriate action."
+
+      - name: Fail if release exists
+        if: env.exists == 'true'
+        run: |
+          echo "Error: Release $VERSION already exists!"
+          exit 1
 
       - name: gh release create
         if: env.exists == 'false' && (env.RELEASE_TYPE == 'final' || env.RELEASE_TYPE == 'post')
